apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-files-local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    # Note that this requires the reader (backend) and writer (worker) to be on
    # the same node. That's OK since this PV is only for local development use.
    # We'll use a different PV for cloud deployment.
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/audiobookify/audio_files
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube
