# This volume stores generated audio files.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-files-local-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /var/lib/audiobookify/audio_files
    type: DirectoryOrCreate