apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-files-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi