# yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: audiobookify
    tier: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: audiobookify
      tier: backend
  template:
    metadata:
      labels:
        app: audiobookify
        tier: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          volumeMounts:
            - name: audio-storage
              mountPath: /audio
            - name: text-storage
              mountPath: /text
          envFrom:
            - configMapRef:
                name: app-config
      volumes:
        - name: audio-storage
          persistentVolumeClaim:
            claimName: audio-files-local-pvc
        - name: text-storage
          persistentVolumeClaim:
            claimName: text-files-local-pvc