apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:15
        command: ['psql', '-h', 'postgres-service', '-U', 'postgres', '-d', 'audiobookify', '-f', '/docker-entrypoint-initdb.d/init.sql']
        env:
        - name: PGPASSWORD
          value: postgres
        volumeMounts:
        - name: init-script
          mountPath: /sql-initialization
      volumes:
      - name: init-script
        configMap:
          name: db-init-sql
      restartPolicy: Never
  backoffLimit: 4