# yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: audiobookify
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: audiobookify
      tier: frontend
  template:
    metadata:
      labels:
        app: audiobookify
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}