apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1 Gi
  hostPath:
    path: /var/lib/audiobookify
    type: DirectoryOrCreate
