apiVersion: v1
kind: PersistentVolume
metadata:
  name: text-files-local-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /var/lib/audiobookify/text_files
    type: DirectoryOrCreate