# yaml
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: audiobookify
    tier: worker
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: audiobookify
    tier: worker