apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: audiobookify
    tier: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: audiobookify
      tier: worker
  template:
    metadata:
      labels:
        app: audiobookify
        tier: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image }}"
          volumeMounts:
            - name: audio-storage
              mountPath: /audio
            - name: text-storage
              mountPath: /uploads/pdfs
          env:
            - name: CELERY_BROKER_URL
              value: "{{ .Values.env.CELERY_BROKER_URL }}"
            - name: CELERY_RESULT_BACKEND
              value: "{{ .Values.env.CELERY_RESULT_BACKEND }}"
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
      volumes:
        - name: audio-storage
          persistentVolumeClaim:
            claimName: audio-files-local-pvc
        - name: text-storage
          persistentVolumeClaim:
            claimName: text-files-local-pvc