backend:
  image: nathanclonts/audiobookify:backend-v0.0.3
  service:
    port: 5000
  replicas: 1

frontend:
  image: nathanclonts/audiobookify:frontend-v0.0.8
  service:
    port: 3000
  replicas: 1

worker:
  image: nathanclonts/audiobookify:worker-v0.0.3
  replicas: 1

postgres:
  image: postgres:15
  service:
    port: 5432
  replicas: 1

redis:
  image: redis:7.0
  service:
    port: 6379
  replicas: 1

service:
  type: LoadBalancer
  port: 80

env:
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/audiobookify"
  REACT_APP_API_BASE_URL: "/api"
  FLASK_ENV: "production"
